// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehSx0YeK_FiEA50BE5VzJskDWMIqXeX4',
    appId: '1:906188246436:web:cfb42ec778efab37fe8531',
    messagingSenderId: '906188246436',
    projectId: 'fir-flutter-codelab-6f60d',
    authDomain: 'fir-flutter-codelab-6f60d.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6f60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBId7YBPW_-xAVh3xu-f_dqpmDSZ3pXyzU',
    appId: '1:906188246436:ios:61a21d8566a7e95bfe8531',
    messagingSenderId: '906188246436',
    projectId: 'fir-flutter-codelab-6f60d',
    storageBucket: 'fir-flutter-codelab-6f60d.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBId7YBPW_-xAVh3xu-f_dqpmDSZ3pXyzU',
    appId: '1:906188246436:ios:61a21d8566a7e95bfe8531',
    messagingSenderId: '906188246436',
    projectId: 'fir-flutter-codelab-6f60d',
    storageBucket: 'fir-flutter-codelab-6f60d.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmix2QzdTPVkV4B50KMYTq9_mvw3ICAXw',
    appId: '1:906188246436:android:5f571f09199fb808fe8531',
    messagingSenderId: '906188246436',
    projectId: 'fir-flutter-codelab-6f60d',
    storageBucket: 'fir-flutter-codelab-6f60d.appspot.com',
  );

}